### ISSUE TITLE
Crash during initializing game phase

### ISSUE THREAD

**Issue by rtngtom** [FireBall1725/ae2ee3emcaddon#3]
Game crashes during startup, Error log attached:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 26/06/15 6:35 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at net.minecraft.item.ItemSlab.func_77667_c(SourceFile:37)
    at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
    at com.pahimar.ee3.exchange.WrappedStack.toString(WrappedStack.java:589)
    at java.lang.String.valueOf(Unknown Source)
    at java.lang.StringBuilder.append(Unknown Source)
    at com.pahimar.ee3.recipe.RecipeRegistry.addRecipe(RecipeRegistry.java:53)
    at com.pahimar.ee3.api.exchange.RecipeRegistryProxy.addRecipe(RecipeRegistryProxy.java:17)
    at com.fireball1725.ae2ee3emcaddon.recipes.RegisterFacade.addItem(RegisterFacade.java:44)
    at com.fireball1725.ae2ee3emcaddon.recipes.RegisterFacade.initRecipes(RegisterFacade.java:27)
    at com.fireball1725.ae2ee3emcaddon.core.ae2ee3emcaddon.postInit(ae2ee3emcaddon.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.item.ItemSlab.func_77667_c(SourceFile:37)
    at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
    at com.pahimar.ee3.exchange.WrappedStack.toString(WrappedStack.java:589)
    at java.lang.String.valueOf(Unknown Source)
    at java.lang.StringBuilder.append(Unknown Source)
    at com.pahimar.ee3.recipe.RecipeRegistry.addRecipe(RecipeRegistry.java:53)
    at com.pahimar.ee3.api.exchange.RecipeRegistryProxy.addRecipe(RecipeRegistryProxy.java:17)
    at com.fireball1725.ae2ee3emcaddon.recipes.RegisterFacade.addItem(RegisterFacade.java:44)
    at com.fireball1725.ae2ee3emcaddon.recipes.RegisterFacade.initRecipes(RegisterFacade.java:27)
    at com.fireball1725.ae2ee3emcaddon.core.ae2ee3emcaddon.postInit(ae2ee3emcaddon.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 746810816 bytes (712 MB) / 1450704896 bytes (1383 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:MaxPermSize=512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 133 mods loaded, 133 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJ   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJ   AM2-Preloader{0.0.2} [AMCore](minecraft.jar) 
    UCHIJ   appliedenergistics2-core{rv2-stable-9} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJ   CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJ   InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) 
    UCHIJ   LanteaCraft-Core{1.0} [LanteaCraft Core](minecraft.jar) 
    UCHIJ   MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) 
    UCHIJ   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJ   MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UCHIJ   NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJ   OpenComputers|Core{1.5.13.28} [OpenComputers (Core)](minecraft.jar) 
    UCHIJ   OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) 
    UCHIJ   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJ   OpenModsCore{0.7.3} [OpenModsCore](minecraft.jar) 
    UCHIJ   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJ   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJ   arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008.jar) 
    UCHIJ   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJ   appliedenergistics2{rv2-stable-9} [Applied Energistics 2](appliedenergistics2-rv2-stable-9.jar) 
    UCHIE   ae2ee3emcaddon{AE2EE3Compat-1.0b2} [AE2 EE3 EMC Addon](AE2EE3Compat-1.0b2.jar) 
    UCHIJ   AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UCHIJ   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJ   BiblioCraft{1.10.4} [BiblioCraft](BiblioCraft[v1.10.4][MC1.7.10].jar) 
    UCHIJ   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJ   Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCHIJ   CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-262.jar) 
    UCHIJ   Forestry{3.5.7.16} [Forestry for Minecraft](forestry_1.7.10-3.5.7.16.jar) 
    UCHIJ   BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) 
    UCHIJ   Highlands{2.2.3} [Highlands](Highlands-1.7.2-v-2.2.3.jar) 
    UCHIJ   BiblioWoodsHighlands{1.4} [BiblioWoods Highlands Edition](BiblioWoods[Highlands][v1.4].jar) 
    UCHIJ   BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) 
    UCHIJ   ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0-81.jar) 
    UCHIJ   ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.1-182.jar) 
    UCHIJ   BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHIJ   BinnieCore{2.0-pre12} [Binnie Core](binnie-mods-2.0-pre12.jar) 
    UCHIJ   Botany{2.0-pre12} [Botany](binnie-mods-2.0-pre12.jar) 
    UCHIJ   ExtraBees{2.0-pre12} [Extra Bees](binnie-mods-2.0-pre12.jar) 
    UCHIJ   ExtraTrees{2.0-pre12} [Extra Trees](binnie-mods-2.0-pre12.jar) 
    UCHIJ   Genetics{2.0-pre12} [Genetics](binnie-mods-2.0-pre12.jar) 
    UCHIJ   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-4.jar) 
    UCHIJ   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJ   Botania{r1.6-194} [Botania](Botania r1.6-194.jar) 
    UCHIJ   CarpentersBlocks{3.3.6} [Carpenter's Blocks](Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
    UCHIJ   ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHIJ   EE3{0.3.507} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.3.507.jar) 
    UCHIJ   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJ   chisel{2.4.0.38} [Chisel 2](Chisel2-2.4.0.38.jar) 
    UCHIJ   ctmlib{1.0.0.3} [CTMLib](Chisel2-2.4.0.38.jar) 
    UCHIJ   cookiecore{1.3.1} [Cookie Core](CookieCore-1.7.10-1.3.1-7.jar) 
    UCHIJ   craftingpillars{1.6.0} [Crafting Pillars Mod](CraftingPillars-1.7.x-1.6.1.jar) 
    UCHIJ   customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d.jar) 
    UCHIJ   digimobs{Beta Bugdate A Hotfix} [Digimobs](Digimobs%28Beta bugdateA%29 Hotfix-1.7.10.jar) 
    UCHIJ   Enchiridion{1.3} [Enchiridion](Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHIJ   Enchiridion2{2.0.2a} [Enchiridion 2](Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHIJ   MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar) 
    UCHIJ   EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UCHIJ   EnderZoo{1.7.10-1.0.11.28} [Ender Zoo](EnderZoo-1.7.10-1.0.11.28.jar) 
    UCHIJ   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJ   extracells{2.2.73} [Extra Cells 2](ExtraCells-1.7.10-2.2.73b129.jar) 
    UCHIJ   ExtraUtilities{1.2.6} [Extra Utilities](extrautilities-1.2.6.jar) 
    UCHIJ   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJ   FinderCompass{1.7.10a} [Finder Compass](FinderCompass-1.7.10.jar) 
    UCHIJ   flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJ   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJ   ForbiddenMagic{1.7.10-0.562} [Forbidden Magic](Forbidden Magic-1.7.10-0.562.jar) 
    UCHIJ   NBTEdit{1.7.2.2} [In-game NBTEdit](Forge_NBTEditv1.7.2.2.zip) 
    UCHIJ   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.345.jar) 
    UCHIJ   GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.345.jar) 
    UCHIJ   Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) 
    UCHIJ   Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) 
    UCHIJ   Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) 
    UCHIJ   Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) 
    UCHIJ   Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) 
    UCHIJ   Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) 
    UCHIJ   Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) 
    UCHIJ   Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) 
    UCHIJ   IGWMod{1.1.3-18} [In-Game wiki Mod](IGW-Mod-1.7.10-1.1.3-18-universal.jar) 
    UCHIJ   ImmersiveEngineering{0.3.0} [Immersive Engineering](ImmersiveEngineering-0.3.0.jar) 
    UCHIJ   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJ   IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHIJ   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJ   journeymap{5.0.1} [JourneyMap](JourneyMap5.0.1_Unlimited_MC1.7.10.jar) 
    UCHIJ   OpenComputers{1.5.13.28} [OpenComputers](OpenComputers-MC1.7.10-1.5.13.28-universal.jar) 
    UCHIJ   LanteaCraft{1.0.0-70} [LanteaCraft](LanteaCraft-1.7.10-70.jar) 
    UCHIJ   MagicBees{1.7.10-2.3.1} [Magic Bees](magicbees-1.7.10-2.3.1.jar) 
    UCHIJ   Mariculture{1.7.10-1.2.4.2a} [Mariculture](Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
    UCHIJ   MariTech{1.0} [Marine Technlogy](Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
    UCHIJ   minechem{5.0.5.398} [Minechem](Minechem-1.7.10-5.0.5.398.jar) 
    UCHIJ   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJ   Morpheus{1.7.10-1.6.4} [Morpheus](Morpheus-1.7.10-1.6.4.jar) 
    UCHIJ   NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) 
    UCHIJ   NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) 
    UCHIJ   NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) 
    UCHIJ   NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) 
    UCHIJ   NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) 
    UCHIJ   neiintegration{1.0.9} [NEI Integration](NEIIntegration-MC1.7.10-1.0.9.jar) 
    UCHIJ   NotEnoughCodecs{0.3} [NotEnoughCodecs](NotEnoughCodecs-1.7.10-0.3.jar) 
    UCHIJ   OpenMods{0.7.3} [OpenMods](OpenModsLib-1.7.10-0.7.3.jar) 
    UCHIJ   OpenBlocks{1.4.3} [OpenBlocks](OpenBlocks-1.7.10-1.4.3.jar) 
    UCHIJ   harvestcraft{1.7.10i} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10i.jar) 
    UCHIJ   PneumaticCraft{1.9.0-85} [PneumaticCraft](PneumaticCraft-1.7.10-1.9.0-85-universal.jar) 
    UCHIJ   rftools{3.10} [RFTools](rftools-3.10.jar) 
    UCHIJ   SpiceOfLife{1.2.3} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.3.jar) 
    UCHIJ   StevesFactoryManager{A93} [Steve's Factory Manager](StevesFactoryManagerA93.jar) 
    UCHIJ   ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) 
    UCHIJ   elysium{1.0} [The Elysium](TheElysium-1.7.x-1.0.3.jar) 
    UCHIJ   WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHIJ   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCHIJ   YABM{1.0.6} [Yet Another Backup Mod](YABM-1.7.10-1.0.6.jar) 
    UCHIJ   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJ   HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.4.13283 Compatibility Profile Context 14.501.1003.0' Renderer: 'AMD Mobility Radeon HD 5000 Series'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-9 for Forge 10.13.2.1291
    Mantle Environment: Environment healthy.
    CoFHCore: -[1.7.10]3.0.2-262
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Mobility Radeon HD 5000 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Thiana** [comment]
This looks like the same issue as http://minecraft.curseforge.com/mc-mods/230951-ae2-ee3-emc-add-on/issues/949. I tracked the problem to the Highlands mod. Remove that and everything works fine.
